language: python
python:
    - "3.6"

cache: pip

before_install:
  - pip install --user awscli # Install AWS cli
  - export PATH=$PATH:$HOME/.local/bin # Add aws to the path.
  # Check that we can login. Requires AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environmental variables.
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t ferret .

script:
  - docker run -t ferret coverage run src/unit_tests.py

after_success:
  - pip install pyyaml coveralls
  # Copy the coverage results file from the Docker container to Travis.
  - docker cp ferret:/usr/src/app/$(docker exec -it ferret bash -c "ls -a .coverage.*" | tr -d '\r') ./
  # Merge the source paths between the newly copied coverage file and Travis.
  - coverage combine
  # Upload to coveralls.
  - coveralls